name: Test

on:
  repository_dispatch:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
      - uses: ./kube_restart.yaml
        secrets: inherit
