name: Test

on:
  repository_dispatch:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    runs-on: ubuntu-latest
    uses: theosanderson/cov2tree/.github/workflows/kube_restart.yaml@master
      secrets: inherit
